---
- name: Search for Next Available IP
  hosts: 172.16.155.215
  connection: local
  gather_facts: false

  tasks:
  - name: Search for Next Available IP
    include_role:
      name: find_next_available_ip
      vars_from: "secret1.yml"
